apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:cM331XqEgXM=,iv:KPWjGFWTde5kXQT1hSekbWAIAm/5yMhV5K0HHtO+k+Q=,tag:Q69Ow5/prVuCI87TQxxh2w==,type:str]
type: Opaque
data:
    password: ENC[AES256_GCM,data:bLXdGrTnD7m9SBfYfUIg9g==,iv:zaZAQkGKQ8BhFuoihWuxJLohIQDbYXUMDQkeMobNgSU=,tag:m/nCAWMGoOGag2MQRssHkA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/sandbox-403215/locations/global/keyRings/kms-sops/cryptoKeys/key-sops
          created_at: "2023-11-10T01:26:54Z"
          enc: CiQADRGgpOvX/Ji5mUvy+Tg1C4/YX6ECynD5Dwe7mGkDphm8TR0SSQCbUbBlYASFkajGUJnT2k3DQV2gRnvqbu4ZTU1zX4m+V1U/pBrbIGaPDzaXafTkKnralqbJzdR3MBcHjBfKGO42oGvO7wLy/RQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T01:26:55Z"
    mac: ENC[AES256_GCM,data:JmNE2RXBGp45FWxALFQAHCRJPFLZMSTHTBtu05BEGnFELOZv4MzPF2VgysFzFzexcUflXiGOqagN52lyVP3hQwOfzN1Wmkh5BiQ0CEDDcnmwfwHNKl6ZVdpWjGOch55h3gxrdh3U7PJE3Z/l9czb7FtKWuM1RvBPs3GhHatLHoc=,iv:qLIuDDcPoFgaALlaVAnel072R1LDMysk2ity0i0BI4c=,tag:KS82taGFJx45mEtoxTEW+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|name)$
    version: 3.8.1
