{{ $chartName := .Chart.Name }}
{{- range $k, $v := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $chartName }}-{{ $k }}
type: Opaque
data:
  {{ $k }}: {{ $v | b64enc }}
---
{{ end -}}
