secrets:
    password: ENC[AES256_GCM,data:Qj1T7+N7j9KDVg==,iv:Vp7hRHlBMWsstueTqe1MpbOMrpNNcLSFoPNDKxYE6EM=,tag:0KFBeOiPxNWZ+F6BXmtMmQ==,type:str]
    apikey: ENC[AES256_GCM,data:Bg6FSM/vkhs=,iv:712/j3o8/Z00yX8rzOn3jsy8HB3kGQOu0O2689fNj2A=,tag:A7KDn6bbiMyrbzAxXztfFA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/sandbox-403215/locations/global/keyRings/kms-sops/cryptoKeys/key-sops
          created_at: "2023-11-10T15:20:53Z"
          enc: CiQADRGgpPRN71hjKuWu0b3xpLkpIjnSa85G6mwwYvr5fnz+zhoSSQCbUbBlEITkjcWba0VoQMvH9es5vPrp6/mTfVsFIx0XF+kS0pv+JjPw2U1MAA3vQndV9+AblbYTG5OScopeo6vOIsQxjxytxms=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T15:20:53Z"
    mac: ENC[AES256_GCM,data:IW/tGlSu7eBEFWREaSV8ul70FCFd6rNLG5YE/bb5zhLedef/ixNGE4M9NHj403bLFK2wKpiCb3OUBS9l0vubZB/CJVR1uEL5TGxRBm83bLYdmjzvoSbMZO8LGmUVrIow1K7tDI3aSyDFZCQgA+S4DPEOym0XBHnMxG0Qsfs6vLg=,iv:GyKsXKSFgIjfNrZbjc3A6fdDtvbmrF+Ro95Impe3KQE=,tag:b7Fl3uY3F39eNkYTyu+L0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
